### PR TITLE
Simplify use of different backends [revised]

### PR DESCRIPTION
**Pull request by igorpisarev**
It's not possible to re-open a closed pull request, so I created this one as a replacement for #9.
The commons-io dependency and redundant data conversion to byte array have been removed (they were accidentally borrowed from the "serializable type" PR).
So the efficiency of reading/writing data blocks is exactly the same as in the current implementation.

Core changes:
* Reorganized the code to minimize code duplication across implementations for different backends
* Extended `N5Writer` interface with `createContainer()` and `removeContainer()` methods
* Added tests for overwriting data blocks and reading/writing group attributes, and extended the test for listing groups

Sorry, the name of the branch is a bit misleading since it doesn't actually contain the AWS S3 implementation. It was included in the commits, but was moved to a separate repository, so only the final state matters.

### CODE REVIEW

**Comment by imagejan** [comment]
@igorpisarev wrote:
> It's not possible to re-open a closed pull request

That's not true: people with write permissions on the repository can re-open the PR as long the the branch it was based on still exists (or gets re-pushed).

**Comment by axtimwalde** [comment]
@igorpisarev What is the rationale to combine `FSReader` and `FSWriter` and to make `LockedFileChannel` its own class?  Any benefits?  Otherwise remove.

**Comment by igorpisarev** [comment]
@axtimwalde Without combining readers/writers I could not add an abstraction layer: `N5Writer extends N5Reader` on the interface level, and if I added `AbstractN5Reader` and `AbstractN5Writer` classes (each implementing the corresponding interface), the `N5FSWriter` implementation would have extended either `N5FSReader & AbstractN5Writer` or `AbstractN5Reader & AbstractN5Writer`, where both of these options are impossible.
`LockedFileChannel` is not exposed to public and is available only within the `fs` package.

**Comment by axtimwalde** [comment]
Closed collaboratively with https://github.com/saalfeldlab/n5/pull/11

**Pull request closed without merging**
